# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example_meta.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='example_meta.proto',
  package='indexer',
  syntax='proto3',
  serialized_options=b'\n\032name.porpoise.service.grpcP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12\x65xample_meta.proto\x12\x07indexer\"@\n\x0e\x45xampleRequest\x12\x0b\n\x03num\x18\x01 \x01(\x05\x12\x13\n\x0bworker_rank\x18\x02 \x01(\x05\x12\x0c\n\x04uuid\x18\x03 \x01(\t\"\x1f\n\x0b\x45xampleMeta\x12\x10\n\x08\x66ilepath\x18\x01 \x01(\t\"\x1f\n\x0fRegisterRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"\"\n\x10RegisterResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x32\x96\x01\n\x0e\x44\x61tasetService\x12\x41\n\x0c\x46\x65tchExample\x12\x17.indexer.ExampleRequest\x1a\x14.indexer.ExampleMeta\"\x00\x30\x01\x12\x41\n\x08Register\x12\x18.indexer.RegisterRequest\x1a\x19.indexer.RegisterResponse\"\x00\x42\x1e\n\x1aname.porpoise.service.grpcP\x01\x62\x06proto3'
)




_EXAMPLEREQUEST = _descriptor.Descriptor(
  name='ExampleRequest',
  full_name='indexer.ExampleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='num', full_name='indexer.ExampleRequest.num', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='worker_rank', full_name='indexer.ExampleRequest.worker_rank', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='indexer.ExampleRequest.uuid', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=95,
)


_EXAMPLEMETA = _descriptor.Descriptor(
  name='ExampleMeta',
  full_name='indexer.ExampleMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='filepath', full_name='indexer.ExampleMeta.filepath', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=128,
)


_REGISTERREQUEST = _descriptor.Descriptor(
  name='RegisterRequest',
  full_name='indexer.RegisterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='indexer.RegisterRequest.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=161,
)


_REGISTERRESPONSE = _descriptor.Descriptor(
  name='RegisterResponse',
  full_name='indexer.RegisterResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='indexer.RegisterResponse.status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=197,
)

DESCRIPTOR.message_types_by_name['ExampleRequest'] = _EXAMPLEREQUEST
DESCRIPTOR.message_types_by_name['ExampleMeta'] = _EXAMPLEMETA
DESCRIPTOR.message_types_by_name['RegisterRequest'] = _REGISTERREQUEST
DESCRIPTOR.message_types_by_name['RegisterResponse'] = _REGISTERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExampleRequest = _reflection.GeneratedProtocolMessageType('ExampleRequest', (_message.Message,), {
  'DESCRIPTOR' : _EXAMPLEREQUEST,
  '__module__' : 'example_meta_pb2'
  # @@protoc_insertion_point(class_scope:indexer.ExampleRequest)
  })
_sym_db.RegisterMessage(ExampleRequest)

ExampleMeta = _reflection.GeneratedProtocolMessageType('ExampleMeta', (_message.Message,), {
  'DESCRIPTOR' : _EXAMPLEMETA,
  '__module__' : 'example_meta_pb2'
  # @@protoc_insertion_point(class_scope:indexer.ExampleMeta)
  })
_sym_db.RegisterMessage(ExampleMeta)

RegisterRequest = _reflection.GeneratedProtocolMessageType('RegisterRequest', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERREQUEST,
  '__module__' : 'example_meta_pb2'
  # @@protoc_insertion_point(class_scope:indexer.RegisterRequest)
  })
_sym_db.RegisterMessage(RegisterRequest)

RegisterResponse = _reflection.GeneratedProtocolMessageType('RegisterResponse', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERRESPONSE,
  '__module__' : 'example_meta_pb2'
  # @@protoc_insertion_point(class_scope:indexer.RegisterResponse)
  })
_sym_db.RegisterMessage(RegisterResponse)


DESCRIPTOR._options = None

_DATASETSERVICE = _descriptor.ServiceDescriptor(
  name='DatasetService',
  full_name='indexer.DatasetService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=200,
  serialized_end=350,
  methods=[
  _descriptor.MethodDescriptor(
    name='FetchExample',
    full_name='indexer.DatasetService.FetchExample',
    index=0,
    containing_service=None,
    input_type=_EXAMPLEREQUEST,
    output_type=_EXAMPLEMETA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Register',
    full_name='indexer.DatasetService.Register',
    index=1,
    containing_service=None,
    input_type=_REGISTERREQUEST,
    output_type=_REGISTERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATASETSERVICE)

DESCRIPTOR.services_by_name['DatasetService'] = _DATASETSERVICE

# @@protoc_insertion_point(module_scope)
